services:
  poost:
    build:
      context: ..  # Context is the project root (one level up)
      dockerfile: docker/Dockerfile # Path to Dockerfile _from_ the context
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info,poost=debug # Example: Set log level for the app
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/info"]