name: Docker Compose CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build images and start all services from docker-compose.yml
      - name: Build & start containers
        run: |
          docker compose \
            --file docker/docker-compose.yml \
            up --build -d