name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt

      - name: rustfmt
        run: cargo fmt --all --check

    #   - name: clippy
    #     run: cargo clippy --all-targets --all-features -- -D warnings

      - name: cargo test
        run: cargo test --workspace --all-features --no-fail-fast
